- name: "Setup Argocd"
  hosts: all
  vars_files:
    - vars.yml
  roles:
    - role: kameshsampath.kubernetes_spices.argocd
  tasks:
    - name: "direnv allow"
      ansible.builtin.command:
        argv:
          - direnv
          - allow
          - "{{ playbook_dir }}"
