---
# roles:
#   - name: kameshsampath.minikube
#     src: https://github.com/kameshsampath/ansible-role-minikube
#     revision: main
collections:
  # - name: kameshsampath.gloo
  #   src: https://github.com/kameshsampath/kameshsampath.gloo
  #   revision: main
  - name: community.crypto
