apiVersion: portal.gloo.solo.io/v1beta1
kind: Portal
metadata:
  name: ecommerce-portal
  namespace: {{ .Release.Namespace }}
spec:
  {{- if .Values.portalSSLEnabled }}
  tls:
    secretRef:
      name: kameshs-me-tls
      namespace: gloo-system
  {{- end }}
  displayName: E-commerce Portal
  description: The Gloo Portal for the Petstore API and much more!
  banner:
    fetchUrl: https://i.imgur.com/EXbBN1a.jpg
  favicon:
    fetchUrl: https://i.imgur.com/QQwlQG3.png
  primaryLogo:
    fetchUrl: https://i.imgur.com/hjgPMNP.png
  customStyling: {}
  staticPages: []
  domains:
  - {{ print "portal." .Values.portalDomain }}
  publishedEnvironments:
  - name: dev
    namespace: default
  allApisPublicViewable: true # this will make APIs visible by unauthenticated users
  {{- if .Values.portalAuthEnabled }}
  oidcAuth:
    clientId: {{ .Values.oidcClientId }}
    clientSecret:
      name: gloo-demos-secret
      namespace: {{ .Release.Namespace }}
      key: client_secret
    groupClaimKey: group
    issuer: {{ print .Values.keycloakURL  "/auth/realms/" .Values.keycloakRealm }}
  {{- end }}
  portalUrlPrefix: {{ .Values.portalUrlPrefix }}

