{{- if and ( .Values.apps.bookinfo.enabled ) ( has "v2" .Values.apps.bookinfo.reviewsVersions ) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bookinfo-reviews-v3
  namespace: {{ .Release.Namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: apps/bookinfo/reviews-v3
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.apps.bookinfo.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}