{{- if .Values.apps.ecommercePortal.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-portal
  namespace: {{ .Release.Namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: charts/portal
    targetRevision: {{ .Values.spec.source.targetRevision }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.apps.ecommercePortal.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}