apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gloo-edge
  namespace: {{ .Release.Namespace }}
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: infrastructure/gloo/edge
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      parameters: []
      valueFiles:
        # The age encrypted secrets.yaml is decrypted using the `key.txt` that # is mounted on to argocd-repo-server pod via  # helm-secrets-private-keys volume
        - secrets+age-import:///helm-secrets-private-keys/key.txt?secrets.yaml
        - values.yaml
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.apps.gloo.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true